### ISSUE TITLE
Benchmarking analogous to decoupleRBench

### ISSUE THREAD

**Issue by erbsl** [saezlab/decoupler-py#1]
Hi all,

Delighted to see that the python implementation runs smoothly and fast so far.
Is also the implementation of decoupleRBench in work/planned?

Cheers

**Comment by PauBadiaM** [comment]
Hi @erbsl ,

Thanks for trying out the package! Unfortunately it is not planned for now. However, one could infer activities in python and then use `decoupleRBench` since it now accepts previously inferred activities. The `run_benchmark` function is now spitted into two components, `run_methods` and `run_eval`. Then, you could reformat the activities obtained in python so that they can be used by `run_eval`. 
Another option would be that you implement the evaluation in python for your specific case, which is not too complicated since it's just a RO and PR curves but it requires times.
Hope this was helpful.

Cheers!

**Comment by erbsl** [comment]
Hi @PauBadiaM

Thanks for the quick reply and pointers, will test it out for my individual cases!
Keep us updated if there will be an implementation!

Cheers and happy programming!

**Comment by PauBadiaM** [comment]
Hi @erbsl 

I have good news for you. We have recently added a flexible benchmarking pipeline, you can check it [here](https://decoupler-py.readthedocs.io/en/latest/notebooks/benchmark.html).
To use it update decoupler to the 1.2.0:
```
pip install decoupler
```
