### ISSUE TITLE
Nan values in benchmarking pipeline still give error - Decoupler v 1.6

### ISSUE THREAD

**Issue by IBMB-MFP** [saezlab/decoupler-py#106]
Hi,

Thanks again for the great software.

I am trying to run the benchmarking pipeline and I would like to feed it in stats from a differential expression analysis conducted with DESeq2. As such the stats contain a lot of NaNs. Previously I had set them to 0 but I saw in the release notes for decoupler v1.5 that 

"The benchmark pipeline now handles methods that provide only positive enrichment scores. **Also added support for nan scores**."

I feel that keeping the NaNs is preferable for fitting the linear models, since giving the NaNs a weight of 0 still contributes to the line fit.

As such I updated decoupler (to v 1.6) and kept the NaN scores in my matrix - but when I run the benchmarking pipeline I still get the error:

"ValueError: mat contains non finite values (nan or inf), please set them to 0 or remove them."

Did I misunderstand the release notes that suggested that NaN would be tolerated in the benchmarking matrix?

Thanks and kind regards,

Marcos

**Comment by PauBadiaM** [comment]
Hi @IBMB-MFP ,

Thanks for raising this up. Now that I look at the release notes they are a bit confusing, sorry!

The note in 1.5 refers to the fact that sometimes methods may output `nan` activity scores for some sources and then the benchmark pipeline would break.

Regarding your question, this can actually be accomplished with the 1.6 version since I added a `dense` argument to the `decouple` function. This argument enables to run methods ignoring zeros in the input `mat`. So you can run you benchmark like this:
```python
decouple_kws={
    'methods' : [''ulm'],
    'consensus': False,
    'dense': True,
}

# Run benchmark pipeline
df = dc.benchmark(..., decouple_kws=decouple_kws)
```
 Note that this will be considerably slower. I'll update the docs so that it is clearer that this is now possible. Hope this is helpful!

**Comment by IBMB-MFP** [comment]
Bon dia Pau,

OK so I did misunderstand! No worries about the release notes. I am glad that this functionality does exist in any case, and thanks for the clear explanation. I will give it a try. I find the benchmarking pipeline runs pretty quickly anyway so if I have to go for a coffee while I wait, so be it!

Thanks,

Marcos
