### ISSUE TITLE
plot_network doesnt return a graph with right node/edge visual styles

### ISSUE THREAD

**Issue by zhaleh-safikhani** [saezlab/decoupler-py#125]
Hi, When I try to use the plot_network function to plot the network, it seems that the visual style properties are not passed to the grid so in my case the resulting network doesnt have the labels and proper coloring scheme (plot attached). 

When I plot the network manually it works fine and it seems that the problem is caused by using grid. I noticed in the code the visual style properties are not passed to the plot. For example if I change your code this way vs={}; vs['vertex_color']=g.vs['color']; ig.plot(g, target=ax1, **vs), the vertices color will be fixed

However, I am wondering how the code works on your side for this tutorial figure
https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html#Transcription-factor-activity-inference

Is it possible that  matplotlib/igraph version plays a role here? 
matplotlib=3.8.1
igraph=0.9.11

![Screen Shot 2024-05-16 at 10 55 45 AM](https://github.com/saezlab/decoupler-py/assets/10283595/ad3d7b95-06db-4c63-9386-c2127287097d)

**Comment by PauBadiaM** [comment]
Hi @zhaleh-safikhani,

Thanks for opening this issue! I've checked and it was a problem with `igraph`'s version, it needs to be `>=0.10.0` to render properly. You will still need to play with the `node_size` parameter since different `igraph` versions render nodes completely different (for `0.10.0` I had to set it to `node_size=0.5`).
I will add the proper version as a requirement for the conda enviroment and add a check for it in the code.
