### ISSUE TITLE
Progeny mouse 'Invalid block type' error

### ISSUE THREAD

**Issue by eaboelno** [saezlab/decoupler-py#128]
Hello Developers,

I have been using decoupler for human data, it works great! but I also have some mouse files I wanted to try out. Though I can download and use the human datasets in progeny and msigdb, but the mouse files are not working.

I tried: 
progeny = dc.get_progeny(organism = 'Mus musculus') and
mouse_msigdb = dc.translate_net(msigdb, target_organism = 'mouse', unique_by = ('geneset', 'genesymbol'))

But I get the error:
BadGzipFile: CRC check failed 0x138e0e05 != 0x46beeabe

I also got errors for mouse:
'Invalid block type' and 'Invalid stored block length', and I get these whether I used development version 1.5.0 or 1.6.0, but with either version I can access the human files.

Could you please help me understand the source of this error and how to overcome it and use the mouse files? 

Thank you,
EA

**Comment by deeenes** [comment]
Hello,

I think this is most likely a corrupt file from a failed download. Easiest is to start over with an empty cache, maybe in your case you can simply remove the `pypath` cache:

If you use Unix:

```
rm -rf ~/.cache/pypath
```

Otherwise:

```
from pypath.share import cache
import shutil

shutil.rmtree(cache.get_cachedir())
```

After deleting the cache, try again loading PROGENy. Make sure you're on a good quality, not too restricted network. If the problem persists, please include a full traceback and the `pypath` log (from the session where the error happened):

```
import decoupler as dc
prm = dc.get_progeny(organism = 'mouse')
# the error happens here
import pypath
pypath.log()
# or, to get the path:
pypath.session._logger.fname
```

**Comment by eaboelno** [comment]
Hello,

Thank you for your response. I have tried the above as you instructed, removed the cache and try the import, with 'mouse', using command:
prm = dc.get_progeny(organism = 'mouse')

First error to install pypath-omnipath, which I do with pip. Then I get:
ValueError: not enough values to unpack (expected at least 1, got 0).

I tried to clear the cache again, and I get a new error for 'Mus musculus':
AttributeError: 'NoneType' object has no attribute 'split'

However, I still am able to import 'dc.get_progeny(organism = 'human')' with no issues and it runs very fast!

pypath.session._logger.fname
gives the output '/dev/null'

Is this the source of the problem, that the log path is directed to an output file that discards the data written to it?

Your help is super appreciated!
Erin

**Comment by eaboelno** [comment]
I also get a similar error when I try msigdb:

mouse_msigdb = dc.translate_net(msigdb, target_organism = 'mouse', unique_by = ('geneset', 'genesymbol'))

ValueError: not enough values to unpack (expected at least 1, got 0)

**Comment by deeenes** [comment]
Hello, I'm sorry to hear it didn't work out. Both error messages suggest a download failure, caused potentially by a variety of reasons, such as wrong configuration of libcurl on your system, or limitations of the network it is connected to, or an issue in our software, due to, for example, updates in third party services. However, without tracebacks the error messages convey no information. To include the traceback, copy everything from your last call until the line stating the exception type, and paste it here between [triple backticks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), to render it as a code block. It should look something like this:

```
import singlecell as sc

w = sc.ScWorkflow()
w.init()

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/denes/singlecell/_workflow.py", line 275, in init
    self.load()
  File "/home/denes/singlecell/_workflow.py", line 646, in load
    self.shorten_condition_names()
  File "/home/denes/singlecell/_workflow.py", line 600, in shorten_condition_names
    self._shorten_names('condition')
  File "/home/denes/singlecell/_workflow.py", line 618, in _shorten_names
    self.adata.obs[key] = self.obs[var_full].map(_method)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denes/.cache/pypoetry/virtualenvs/singlecell-kT1YP2rc-py3.11/lib/python3.11/site-packages/pandas/core/series.py", line 4700, in map
    new_values = self._map_values(arg, na_action=na_action)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denes/.cache/pypoetry/virtualenvs/singlecell-kT1YP2rc-py3.11/lib/python3.11/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/denes/.cache/pypoetry/virtualenvs/singlecell-kT1YP2rc-py3.11/lib/python3.11/site-packages/pandas/core/algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
  File "/home/denes/singlecell/_workflow.py", line 607, in <lambda>
    (lambda x: method[x])
               ~~~~~~^^^
KeyError: 'OE_CTRL'
```

Note, in the beginning we see the code that lead to the error, then the trace begins with the line `Traceback (most recent call last):`, and ends with the name and message of the exception (above it's `KeyError...`). In between there are 10 calls, each pointing to a specific line of a specific file: this is the call stack, something essential to understand and troubleshoot any error. 


We could get even more useful information from the log. Indeed, `decoupler` sets the logfile of `pypath` to `/dev/null`, this is not the cause of any error, it simply disables logging into a file. I recommend setting a log file after importing `decoupler`:

```
import decoupler as dc
import builtins
builtins.PYPATH_LOG = './pypath.log'

prm = dc.get_progeny(organism = 'mouse')

# here the error happens,
# please copy the full traceback and include it in your next answer
```

Then open the file `pypath.log` in your working directory, and include its contents in your next answer. You can also read the logfile by `pypath.log()`:

```
import pypath
pypath.log()
```
