### ISSUE TITLE
global regulation

### ISSUE THREAD

**Issue by erbsl** [saezlab/decoupler-py#13]
Hi everyone

Great to see that the package gets some recognition.

I have a theoretical question regarding the TFA inference methods. Do you have any experience/recommendation if/how to deal with potential global regulation (e.g. growth rate dependence of RNA-Seq data)?

Is this usually not a problem for TPM-normalized data/your method compendium or do you account for it during pre-/postprocessing?

Thanks a load!

**Comment by PauBadiaM** [comment]
Hi @erbsl,

Thanks for the question! `decoupler` is agnostic to the type of data processing or normalization, in the notebooks we show some examples, but we leave that to the user's decision. While it is true that different normalization strategies might change the results, since footprint methods are quite robust to noise, even if a single gene changes a lot its value, the inferred score will be similar. To answer your question, use the processing and normalization that you feel is best for your data.
Hope this was helpful!

**Comment by erbsl** [comment]
Hi @PauBadiaM

Thanks for the quick response! Maybe I misunderstand you and that's what you were alluding to: I am not talking about noise in single genes but about global effects on RNA expression in samples with different growth rates (Growth rate correlates e.g. with availability of expression machinery such as RNAP; which correlates with gene expression). => expression is sometimes is described as a function of global (e.g. by expression machinery availability) and specific (e.g. by TFs) regulation.
If that's what you are alluding to, then everything's clear, otherwise I'd be happy to learn about your experiences with such global effects!

Thanks a lot

**Comment by PauBadiaM** [comment]
Hi @erbsl 

If you have information about the growth rate across samples you could run regress this variable out on your data before running `decoupler`, either at the normalized data or at the contrast level. Other than that, decoupler methods don't correct for such global effects I'm afraid.

**Comment by erbsl** [comment]
Hi @PauBadiaM 

Okay, still thanks a lot. Great work!

Cheers
