### ISSUE TITLE
psbulk_counts are associated with top PCs

### ISSUE THREAD

**Issue by singlecellfan** [saezlab/decoupler-py#138]
Hi,

first of all thanks for the great documentation.

I am running the pseudobulk analysis and I found the pseudobulk_counts to be signficantly associated with the top PC which thus also leads to the separation of samples (which is not really wanted, as they should separate based on the cell type).
<img width="533" alt="Screenshot 2024-06-26 at 17 54 05" src="https://github.com/saezlab/decoupler-py/assets/79158757/a06607bc-cd98-4135-a6aa-c195b732e940">

Two question:
1. Is it possible to circumvent this by some sort of normalization?
2. If not, would the pseudobulk counts affect the results of the downstream analyses?

Thank you!

**Comment by PauBadiaM** [comment]
Hi @singlecellfan,

> first of all thanks for the great documentation

Thank you for using it!

> Two question:
> 1. Is it possible to circumvent this by some sort of normalization?
> 2. If not, would the pseudobulk counts affect the results of the downstream analyses?

What seems to be happening is that you have cell type annotations that have large differences in total counts. This can happen because of a technical artifact, or because it is biologically relevant, for example, megacaryocytes will have smaller numer of reads, or cancer cells may have larger.

Regarding the normalization it does not really matter since for the differential expression analysis we use DESeq2 which works at the count level. Most importantly, the gene expression contrast is performed inside each cell type cluster between conditions, so at this level it might be the case that you don't have significant differences in total number of counts. Just in case, I would repeat the plot but subsetting for each cell type (rerunning the PCA etc.), there you should see that the number of counts is not significant. In case it remains significant, you can add it as a covariate to the DESeq2 model to regress it out.

Hope this is helpful!

**Comment by singlecellfan** [comment]
Thanks for getting back to me so quick!

I checked again and it seems that the psbulk_counts actually lead to a separation within the cell types. I have attached the plot. 

<img width="696" alt="Screenshot 2024-06-27 at 11 19 08" src="https://github.com/saezlab/decoupler-py/assets/79158757/2b1f86e1-2ed0-418f-ac6d-286ea4bb1911">

However, I agree that based on your explanation it should not affect the downstream analyses with DESeq2.

> In case it remains significant, you can add it as a covariate to the DESeq2 model to regress it out. >

Would you then just add the psbulk_counts as continous factor when creating the DESeqDatasSet?

**Comment by PauBadiaM** [comment]
Huh interesting! It might be biological since it is not associated with the batch. Maybe in your conditions one pushes the cells to express more reads in general?

I would run it with and without adjusting for the total number of counts and compare the results. Also, I would not add it as a continuous factor but rather a categorical one, for example, low/high, or low/medium/high, you can check the distribution of counts to assess how many categories would make sense.

**Comment by singlecellfan** [comment]
Yes, it seems to be really biological but not really really to the conditions.

Thanks for the suggestion! Is there a specific reason you would run it as a categorical variable instead of a continous factor?

**Comment by PauBadiaM** [comment]
No problem! Based on DESeq2 documentation, see [here](https://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#how-can-i-include-a-continuous-covariate-in-the-design-formula).
