### ISSUE TITLE
Confidence levels

### ISSUE THREAD

**Issue by ktroule** [saezlab/decoupler-py#16]
I have observed that neither the `R` nor `python` version of `decoupler` provides the regulons with confidence level E.
Why is this so?

The only way to retrieve these regulons is through the R `dorothea` library.

On the other hand, when using a version of python earlier than 3.8  the function `summarize_acts()` will yield the same value for the whole row. I think this value corresponds to the mean value of the mean of all regulons within each row.

**Comment by PauBadiaM** [comment]
Hi @ktroule 

Thank you for your question. 

Neither R or python version of decoupler provide the regulons with confidence level E because both packages leverage OmniPath to fetch this information, and these regulons are not available in there for two reasons. First, these regulons can be extremely big (more than 1k target genes) and slow down the responsiveness of the OmniPath server. Second, these regulons were extracted using the GRN inference algorithm ARACNE, which in benchmarks it has been shown that it may perform poorly (https://www.nature.com/articles/nmeth.2016). In case you still want data-driven regulons, you could use more modern methods such as SCENIC or CellOracle which you can merge with dorothea. In case you want to use the old version of dorothea, you can open it in the R package, save it as a csv and open it in R or Python.

Regarding the summarize_acts, I actually introduced a bug by trying to make it retro-compatible with older versions of numpy. I fixed the bug in the main branch, you can install it by running:
```
pip install git+https://github.com/saezlab/decoupler-py
```

Hope this was helpful. Let me know if you have any more questions.

**Comment by ktroule** [comment]
Hi Pau.

Thanks for your answer it has clarified and confirmed some of my guesses about my main question.

Regards.
