### ISSUE TITLE
Pseudobulk issue?

### ISSUE THREAD

**Issue by jackbrougher** [saezlab/decoupler-py#2]
Hello,

I'm running into an issue when I try to generate a pseudobulk dataframe. 

I'm currently running the code:

```padata = dc.get_pseudobulk(adata, sample_col='sample', groups_col='bulk_labels', min_prop=0.01, min_smpls=1)```

Where both sample_col and groups_col are found in the obs of my adata.

I'm receiving the error below when I run the code:

```ValueError: could not broadcast input array from shape (378,17) into shape (17,)```

I know I've set the min_prop and min_smpls low, but that was just out of initial testing/exploration.

**Comment by PauBadiaM** [comment]
Hi @jackbrougher,

Thanks for checking out the package! What version of decoupler are you using? I would recommend installing the latest one using:
```
pip install git+https://github.com/saezlab/decoupler-py
```
There was a bug in the `get_pseudobulk` function in version `1.0.0` that should be fixed now. Else, just curious, what is your `bulk_labels` indicating, cell type?

**Comment by jackbrougher** [comment]
That checks out! I updated and the command ran! Now I just need to figure out where I'm off before that to be getting an empty dataframe when computing DEA's. 

And yep - bulk_labels is my cell type label.

**Comment by PauBadiaM** [comment]
You can get an empty data-frame for different reasons, actually I will implement some warnings for when these cases happen to make it more informative. The reasons can be:

- You don't have enough samples to do a comparison. To make one, you need at least 2 samples of each group (at least 4 samples in total). 
- The `condition` or the `reference` labels are not in `condition_col`.
- For now `group_col` and `condition_col` need to be different. However, today I will implement it so that one can compute DEG of groups (cell types) without a  `condition_col` (disease), this would allow to extract cell type markers at the pseudo-bulk level (I need to test if it makes sense first though).

Maybe you could post the line of code that you are using so that I can see it.

**Comment by PauBadiaM** [comment]
I added some warnings in the function to better know what is going wrong, you can test it if you install the latest version again. Hopefully it makes it clearer!
