### ISSUE TITLE
Pseudobulk improvements

### ISSUE THREAD

**Issue by grst** [saezlab/decoupler-py#29]
As decoupler appears to become the go-to method of scverse to generate pseudobulk (e.g. https://github.com/theislab/single-cell-best-practices/issues/141), I suggest a few improvements to the pseudobulk function in decoupler: 

1) **documentation**

   I feel a few points could be documented better: 
    - How are the cutoffs defined, e.g. does `min_prop` mean *one group* needs to have more expressing cells than this fraction, or all cells (same applies for the other filtering attributes)?
    - How were the default values chosen, and are there recommendations to choose other values for certain use-cases? To me, 0.2 seems a bit conservative for general usage, but maybe you had reasons for this value. 

2) **allow to specify a callback function for `mode`**

   Taking a callback in addition to sum/mean/median would allow maximum flexibility. 
   A usecase that comes to my mind is to compute the fraction of cells expressing a gene. This could be used to make dotplots of pseudobulk (`mode = lambda x: np.sum(x >= 1) / len(x)`)
   
   An extension of this idea is to allow passing a `Dict[str, Callable]` to allow different aggregations into different layers, e.g. 
   
   ```python
   dc.get_pseudobulk(adata, ..., mode = {
       'counts': np.sum, 
       'fractions': lambda x: np.sum(x >= 1) / len(x)
   })
   ```
   
3) **allow to group by multiple columns**

   I commonly need pseudobulk by sample, condition *and* cell-type. It would be great if `groups_col` could take multiple keys, e.g.
   ```python
    pb = dc.get_pseudobulk(adata, sample_col="patient", groups_col=["cell_type", "condition"])
    ```

4) **include stats in `.obs`: `n_cells`**

   It would be nice to generate an additional column in `obs` that stores how many cells were included into the pseudobulk sample. This may be useful as an additional covariate when performing differential expression analysis. 

CC @Zethson

**Comment by PauBadiaM** [comment]
Hi @grst and @Zethson,

Thanks for the interest! Regarding your questions:

**1. documentation**

> How are the cutoffs defined, e.g. does min_prop mean one group needs to have more expressing cells than this fraction, or all cells (same applies for the other filtering attributes)?

`min_prop` refers to the proportion of cells that express a gene (non-zero value) in a sample-group pair. If `groups_col` is `None`, then its just at the sample level. This is also the case for `min_cells` and `min_counts`. `min_smpls` is done at the group level instead.  I will add this to the docs. 

> How were the default values chosen, and are there recommendations to choose other values for certain use-cases? To me, 0.2 seems a bit conservative for general usage, but maybe you had reasons for this value.

The default values were chosen based on different datasets that I'm working on, but they are arbitrary. As a quality check, I was checking the results of DEA, if logFC exploded that means that I was selecting noisy genes only expressed in few samples and cells of a group. Here is an example of how it looks with `min_prop=0.05` and `min_smpls=1` for the B-cells in the COVID dataset used in the [pseudobulk vignette](https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html): 
![image](https://user-images.githubusercontent.com/44896790/223386831-c06738e8-164b-4b69-9fa3-e54d00d41bc9.png)
With stricter values, this is how it looks:
![image](https://decoupler-py.readthedocs.io/en/latest/_images/notebooks_pseudobulk_21_0.png)
For DEA this is a possible approach but it is very hard to come up with good default parameters for each use case.

**2. Allow to specify a callback function for mode**

> Taking a callback in addition to sum/mean/median would allow maximum flexibility.
A usecase that comes to my mind is to compute the fraction of cells expressing a gene. This could be used to make dotplots of pseudobulk (`mode = lambda x: np.sum(x >= 1) / len(x)`)

I like this idea a lot! Although there might be some problems with the checks I do. I added them so that users by default can't do the sum of counts with the scaled `.X`, something I observed that was quite common, but I could make that if they use a callback function they are disabled so no problem.

> An extension of this idea is to allow passing a Dict[str, Callable] to allow different aggregations into different layers, e.g.

Sound good too! I also have a `swap_layer()`([docs](https://decoupler-py.readthedocs.io/en/latest/generated/decoupler.swap_layer.html#decoupler.swap_layer)) function that could come in handy if users what to change the one they are using.

**3. Allow to group by multiple columns**

> I commonly need pseudobulk by sample, condition and cell-type. It would be great if groups_col could take multiple keys, e.g.

Easy enough to implement.

**4. include stats in `.obs`: `n_cells`**

> It would be nice to generate an additional column in `obs` that stores how many cells were included into the pseudobulk sample. This may be useful as an additional covariate when performing differential expression analysis.

Love this idea! This could be done at the `var` level too. Then, they could also be used as quality control metrics to check and if needed, change the used cutoffs.

**Comment by PauBadiaM** [comment]
Hi @grst,

After working on it I've made some changes on how we do pseudobulk:

- By default, now it does not filter features. I've observed that the default values might have been too stringent. Additionally, people are mainly using edgeR's filtering strategy which differs from the one we have. For these reasons, I've decided to perform the filtering of features into two separate functions, `filter_by_expr` (edgeR) or `filter_by_prop`(decoupler), then people can choose or even perform both. I've also added plotting functions to better decide which thresholds to use as shown in the [vignette](https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html#), or here as an example, edgeR's filtering strategy:
![qc_features](https://decoupler-py.readthedocs.io/en/latest/_images/notebooks_pseudobulk_24_0.png)
- The new object now contains quality control metrics such as the number of cells per sample (`psbulk_n_cells`), the number of counts per sample (`psbulk_counts`) and the proportion of cells that expressed that gene (`psbulk_props`). I've also added plots to decide which samples to drop:
![qc_samples](https://decoupler-py.readthedocs.io/en/latest/_images/notebooks_pseudobulk_18_0.png)
For example here it might be good to filter out samples that contain less than 10 cells (mainly platelet cells).

- Now `groups_col` accepts take multiple keys as we discussed.
- Now `mode` accepts a dictionary of callable functions. The resulting profiles will be stored in `.layers`.

I've also updated the vignettes to use PyDESeq2 for DEA and added more plotting functions if you are interested. All changes additions are reported in the [release notes](https://decoupler-py.readthedocs.io/en/latest/release_notes.html#id1).

Regarding your quesiton
> I'm not sure if I got this. By "sample-group pair" I believe you are referring to what will be one row in obs of the generated pseudobulk AnnData. Does this mean that if the min_prop threshold is exceeded in at least one of the sample-group pairs, the gene will be included?

Exactly! If the min_prop threshold is exceeded in at least N sample-group pairs of group M.

**Comment by Zethson** [comment]
CC @alitinet

**Comment by grst** [comment]
Nice work!

@BorisMuzellec, you might be interested in the [updated vignette](https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html) now showcasing how to use decoupler+PyDESeq2 for pseudo-bulk single-cell analysis.

**Comment by sruthi-hub** [comment]
Thanks a lot for collaborating with @BorisMuzellec and integrating pyDEseq2 with DecoupleR, super helpful for the research community!

I am using this tool and facing some issues when I run dds.deseq2 as per the tutorial. Wasn't sure if I should post here on pydeseq2. 

I created pseudobulked anndata and made the DeseqDataSet. When I run dds.deseq2(), it gives me a Key Error as follows. 
When I looked into the function deeper and ran each step individually, it seems like the dds object does not get assigned with new "obsm" or "layers" results from 'fit_size_factors()' or 'fit_gene_dispersions()'. 

When I run the assignment line separately, it does not work either, even though the value being assigned in not empty.

![image](https://user-images.githubusercontent.com/51859127/228335289-0ea60ed8-9472-42de-984f-4b8a07a87ff3.png)

![image](https://user-images.githubusercontent.com/51859127/228335976-b781ac79-354c-4b4b-9441-90503d4ca7e4.png)

Could you point out if I am missing something?

**Comment by grst** [comment]
Hi @PauBadiaM, 

we've started using the latest dev version and the new pseudobulk functionality and it works great! 
Could you put that into a release soon-ish? 

Best, 
Gregor

**Comment by rasmirnov** [comment]
Hello @PauBadiaM,

I'm getting an error `ValueError: Grouper and axis must be same length` when I group data by multiply variable. I've tried with one and everything worked fine, but not with a list..

Here is my code:
`pdata = dc.get_pseudobulk(adata,
                          sample_col='sample',
                          groups_col= ['cell_type', 'organ'],
                          layer='counts',
                          mode='sum',
                          min_cells=10)`

Will be glad for any help!
Roma

**Comment by grst** [comment]
One small comment on the tutorial (and/or the respective function docstring): 

I would find it useful to have a bit more details of how to interpret the `plot_filter_by_expr` plot. I as a bit lost in the beginning. In particular, what do the dashed lines represent, and how exactly does this help determining thresholds? 
![image](https://user-images.githubusercontent.com/7051479/233353298-bf790e3b-f682-474c-a1cc-9339058aaef3.png)

**Comment by PauBadiaM** [comment]
Sorry for the late reply. Glad it worked @rasmirnov! @grst I need to finish something else first but I'm working on the release to pypi, I'll also update the docs to make the filtering clearer.

**Comment by PauBadiaM** [comment]
Finally had time to update the docs and make the release, closing this for now.

**Comment by mikelkou** [comment]
Hi @PauBadiaM,
That's great!
It is already next Tuesday (13th of June) at 18.00. Let us know if you can make it. :)

**Comment by PauBadiaM** [comment]
Sure no problem, next Tuesday works.
