### ISSUE TITLE
Please push version 1.4.0 to pypi, only 1.3.4 is available

### ISSUE THREAD

**Issue by pcm32** [saezlab/decoupler-py#37]
Hi there,

thanks for this toolkit, I was trying your pseudo bulk methods from the latest pypi, but it is missing certain things compared to the docs. I noticed then that the version on pip is not the latest release (1.4.0) but only 1.3.4, could please push 1.4.0.

Thanks!

**Comment by Zethson** [comment]
@PauBadiaM Do you have an ETA for the next release? I'd love to point to a stable version of decoupler for my dependencies

**Comment by deeenes** [comment]
Hello @Zethson, We are waiting for an update in the [OmniPath web service client](https://github.com/saezlab/omnipath) in order to make sure we use our new TF regulon resource CollecTRI in a correct way for TF activity inference. This update will happen within days, and then both packages will be updated in PyPI. Apologies for the delay, and I'll let you know here once we're ready.

**Comment by PauBadiaM** [comment]
@Zethson `decoupler==1.4.0` is finally available through [pip](https://pypi.org/project/decoupler/1.4.0/), sorry for the delay!
