### ISSUE TITLE
run_mdt: module has no attribute

### ISSUE THREAD

**Issue by erbsl** [saezlab/decoupler-py#4]
Hi decoupler enthusiasts,

I am playing around with decoupler using version 1.1.0 and noticed an issue with mdt. I cannot run_mdt (neither via decouple nor via run_mdt). OP: AttributeError: "module 'decoupler' has no attribute 'run_mdt'".
Also quickly checked show_methods(), where run_mdt also was not listed.
Module exists in package folder though.

Cheers

**Comment by PauBadiaM** [comment]
Hi @erbsl,

This might be caused because you don't have `skranger` installed. I didn't add it as a required dependency because it doesn't work in windows yet (the main author was working on it though) and it's just one method. This might be the case for `run_udt` with `sklearn`. 
To solve this just run:
```
pip install skranger
pip install sklearn
```
And then restart your kernel or run a new session.

I need to think of a better way of handling this, like prompting a warning asking to install the packages.
Hope this was helpful!

Cheers!

**Comment by erbsl** [comment]
Ah, @PauBadiaM 
Thanks a lot, this clarifies why it did not work!

Keep up the good work!
