### ISSUE TITLE
run_mlm function process

### ISSUE THREAD

**Issue by elektrafying2000** [saezlab/decoupler-py#42]
Hi! I was wondering if you could help me understand how the multivariate linear model works for pathway activity inference. I understand that the independent variables are interaction weights and the dependent variable the gene expression. But if someone could write a step-by-step of the function's process from input to output, that would be greatly appreciated!:)

**Comment by PauBadiaM** [comment]
Hi @elektrafying2000,

I previously explained how the Univariate Linear Model (`ulm`) works in this [thread](https://github.com/saezlab/decoupler-py/issues/21#issuecomment-1280503031). The Multivariate Linear Model (`mlm`) is just an extension of `ulm`, the difference is that it uses all pathways at the same time during modeling, instead of doing it one by one like `ulm`. Hope this is helpful, please let me know if you have more questions.

**Comment by elektrafying2000** [comment]
Thank you so much for the insight and for taking the time to explain! The explanation was super clear:).
