### ISSUE TITLE
Are dc.run_consensus p-values valid?

### ISSUE THREAD

**Issue by pcm32** [saezlab/decoupler-py#44]
I see that on the [pseudo-bulk notebook](https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html) `dc.run_consensus` is used twice without paying much attention to the pvals results generated. Is it that these p-values are meaningless due to the method used to merge the results between different methods? or why are they neglected in the tutorial?

Thanks!

**Comment by PauBadiaM** [comment]
Hi @pcm32,

Sorry for the late reply and thanks for the question. As you mention, when using the consensus score the obtained p-values are just the mean p-value across methods so it is not that informative. As an alternative, if significance filtering is of interest, I would recommend to either use `ulm` or `mlm` insted since their enrichment score (t-values) are directly linked to the obtained p-value. I've updated the vignettes accordingly.
Hope this is helpful!

**Comment by pcm32** [comment]
Thanks, if you have updated the vignettes / docs I think we can close this issue.
