### ISSUE TITLE
Pseudobulk looses some samples

### ISSUE THREAD

**Issue by grst** [saezlab/decoupler-py#57]
**Describe the bug**
When creating a pseudobulk object from an AnnData object that contains negative values, some samples are silently excluded. 

While for DE analysis, it might not be intended to use negative values, when aggregating scaled values by mean I think this should still work. 

**To Reproduce**
```python
import decoupler as dc
import scanpy as sc
import numpy as np

np.random.seed(42)

adata = sc.datasets.pbmc3k()
# assign random sample id
adata.obs["sample_id"] = np.random.randint(low=1, high=6, size=adata.shape[0]).astype(str)
sc.pp.scale(adata)

pb = dc.get_pseudobulk(adata, sample_col="sample_id", groups_col=None, mode="mean", skip_checks=True)

adata.obs["sample_id"].unique()
# array(['4', '5', '3', '2', '1'], dtype=object)

pb
# AnnData object with n_obs × n_vars = 3 × 16634
#    obs: 'sample_id', 'psbulk_n_cells', 'psbulk_counts'
#    var: 'gene_ids', 'mean', 'std'
#    layers: 'psbulk_props'

assert pb.shape[0] == adata.obs["sample_id"].nunique()
```
```pytb
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[40], line 1
----> 1 assert pb.shape[0] == adata.obs["sample_id"].nunique()

AssertionError: 
```

**Expected behavior**
n_obs of the output anndata object always equals to the number of unique values in the grouping variable. 

**System**
 - decoupler installed from main branch commit b38c07a167699fdef7a28c56cdab9fd05e7a9a53

**Comment by PauBadiaM** [comment]
Hi @grst ,

Good catch! Thanks for raising this issue. The problem was the filter parameter `min_count=1000`. This basically check that the sum of the counts across the sample's cells reach at least 1000 (`count < min_counts`). In your case, setting it to 0 also did not work since you values can be negative after summing. Now the condition uses the absolute value (`abs(count) < min_counts`), so now doing `min_count=0` works for me with your example. Please install the latest commit and let me know how it goes!

BTW, just in case you want to keep all samples always, set also `min_cells=0` since by default is set to 10 and sometimes you might get samples that have less.

**Comment by grst** [comment]
Thanks, I totally overlooked the `min_count` option. With your fix setting it to 0 also works for negative values.
