### ISSUE TITLE
dc.run_mlm() and dc.get_gsea_df()

### ISSUE THREAD

**Issue by dyinboisry4u** [saezlab/decoupler-py#65]
**Describe your question**
Hi, thanks for the great tool, I have several questions: 
1. How to choose the progeny top terms in `dc.get_progeny()`? I found set `top=100` to `top=500` will get a different result 
2. For `dc.run_mlm()` to get the pathway activity for each cell(cell level) with subcluster annotation:
  i. Is it reasonable for just compare `mlm_estimate` across each subclusters and get the mean of each subcluster value to plot matrixplot? I found the mean/medain of some pathway have non significant `mlm_pvals`.
  ii. Is it a better choice for see subcluster as condiction (like set subcluster A to condition A and other subclusters to condition B) to do pseudo-bulk level `dc.run_mlm()`, I find the result is very close to cell level.
3. For `dc.get_gsea_df()` and `dc.run_gsea()`:
  i. I can not run `dc.run_gsea()` for each cell, I'll get the `ZeroDivisionError`. 
  i. For pseudo-bulk, I have two conditions(`health` and `disease`) and each condition has two time points(`before` and `after` treatment). I want to get the difference of `before and after treatment` between two conditions. If I don't filter by `dc.filter_by_expr(pdata, group='time_point', min_count=10, min_total_count=15)` for each group, `dc.get_gsea_df()` also get error. But if I do filter, the backgrounds of two conditions will be different, is acceptable?

**Comment by PauBadiaM** [comment]
Hi @dyinboisry4u,
Thanks for using it!
1. Indeed, changing the `top` number changes the results. This is an arbitrary choice unfortunately, and it depends on the gene coverage available. For example, for single-cell datasets, where we have a lot of dropouts, we recommend increasing the number of genes to around 1000. Currently we don't have a best practice on how many genes to select, but we are working on a benchmark to determine it.
2. Enrichment analysis can be ran at the observation (cluster) or at the contrast level depending on what you want to do. For example, at the observation level you could use it to cluster your cells. But if you are interested in knowing the differences, its better to run enrichment on the contrast results and see what is up/down in each cluster.
3. 1. You might need to increase the number of permutations in `gsea`, although personally I wouldn't run `gsea` at the cell level since it might take too long, instead I would run `ulm` for similar results (and possibly better according to the benchmark we ran in the `decoupler` manuscript). 
    2. Yes this is acceptable, in the end for DEA you want to test genes that can be tested, it can happen that in one condition some genes are just not expressed at all and therefore you cannot even get a log fold change for those.

Hope this was helpful and sorry for the late reply, I was on holidays
